name: password_vault
description: A flutter application to store and manage passwords offline and securely.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+2

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Flutter essentials
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter 
  
  # UI Theme and Style related packages
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.2.2 
  flutter_easyloading: ^3.0.5 
  video_player: ^2.10.0
  flutter_speed_dial: ^7.0.0
  
  # State management and data handling packages
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  hive: ^2.2.3 
  hive_flutter: ^1.1.0 
  go_router: ^17.0.0 

  # System and device related packages
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  android_intent_plus: ^6.0.0
  device_info_plus: ^12.2.0
   
  # Utility packages
  file_picker: ^10.3.3 
  uuid: ^4.5.2
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  local_auth: ^3.0.0
  local_auth_android: ^2.0.0
  local_auth_darwin: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/images/svg/
    - assets/gifs/
